#!/bin/bash -i
HNAME=8.8.8.8
count=2 # Send only two pings.
if ping -c $count "$HNAME" 2> /dev/null
then
    echo "\"$HNAME\" still up and broadcasting spam your way."
else
    echo "\"$HNAME\" seems to be down. Reloading."
    sudo service network-manager restart
fi
